services:
  db:
    image: postgres:14.4
    container_name: db
    environment:
      - POSTGRES_USER=user_db
      - POSTGRES_PASSWORD=11235
      - POSTGRES_DB=omapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: web
    command: python3 -u manage.py runserver
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
